#!name=uv-module
#!desc=自定义模块，覆盖梯子分组、规则等


[Rule]
DOMAIN-KEYWORD,tymetro,DIRECT
DOMAIN-KEYWORD,hushed,TG
RULE-SET,https://raw.githubusercontent.com/rogetsun/proxy-config/refs/heads/main/shadowrockets/talkatone-rule-set.list,talkatone
RULE-SET,https://raw.githubusercontent.com/rogetsun/proxy-config/refs/heads/main/shadowrockets/telegram-rule-set.list,TG
RULE-SET,https://raw.githubusercontent.com/rogetsun/proxy-config/refs/heads/main/shadowrockets/openai-rule-set.list,openai

RULE-SET,https://raw.githubusercontent.com/rogetsun/proxy-config/refs/heads/main/shadowrockets/binance-rule-set.list,binance
RULE-SET,https://raw.githubusercontent.com/rogetsun/proxy-config/refs/heads/main/shadowrockets/github-rule-set.list,GitHub