#!name=uv-module
#!desc=自定义模块，覆盖梯子分组、规则等

[Rule]
DOMAIN-KEYWORD,tymetro,DIRECT
#DOMAIN-KEYWORD,hushed,🇺🇸 美国
DOMAIN-KEYWORD,hushed,美国
RULE-SET,https://raw.githubusercontent.com/rogetsun/proxy-config/refs/heads/main/shadowrockets/talkatone-rule-set.list,美国家宽
#RULE-SET,https://raw.githubusercontent.com/rogetsun/proxy-config/refs/heads/main/shadowrockets/talkatone-rule-set.list,家宽
RULE-SET,https://raw.githubusercontent.com/rogetsun/proxy-config/refs/heads/main/shadowrockets/binance-rule-set.list,binance